name: Release and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comparing versions

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Publish to NPM
        id: publish
        run: |
          # Run the publish command and capture its output
          PUBLISH_OUTPUT=$(bun run publish)
          echo "publish_output<<EOF" >> $GITHUB_OUTPUT
          echo "$PUBLISH_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create deployment summary
        run: |
          echo "## 🚀 Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Release Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Tag:** ${{ github.event.release.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Name:** ${{ github.event.release.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Body:**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ github.event.release.body }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          echo "### Published Packages" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.publish.outputs.publish_output }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          echo "### Build Status" >> $GITHUB_STEP_SUMMARY
          echo "✅ All checks passed successfully" >> $GITHUB_STEP_SUMMARY
          echo "- Build completed" >> $GITHUB_STEP_SUMMARY
          echo "- Tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- Linting passed" >> $GITHUB_STEP_SUMMARY
          echo "- Packages published" >> $GITHUB_STEP_SUMMARY 